apiVersion: v1 
kind: Pod
metadata:
  namespace: test
  name: test
spec:
  containers: 
  - name: busybox
    image: busybox
    stdin: true
    tty: true
    resources:
      limits: 
        cpu: "200m"
        memory: "1Gi"
